<template>
  <div>
    <body class="demo-magneto">
    <svg class="hidden">
      <symbol id="icon-arrow" viewBox="0 0 24 24">
        <title>arrow</title>
        <polygon points="6.3,12.8 20.9,12.8 20.9,11.2 6.3,11.2 10.2,7.2 9,6 3.1,12 9,18 10.2,16.8 "/>
      </symbol>
      <symbol id="icon-drop" viewBox="0 0 24 24">
        <title>drop</title>
        <path d="M12,21c-3.6,0-6.6-3-6.6-6.6C5.4,11,10.8,4,11.4,3.2C11.6,3.1,11.8,3,12,3s0.4,0.1,0.6,0.3c0.6,0.8,6.1,7.8,6.1,11.2C18.6,18.1,15.6,21,12,21zM12,4.8c-1.8,2.4-5.2,7.4-5.2,9.6c0,2.9,2.3,5.2,5.2,5.2s5.2-2.3,5.2-5.2C17.2,12.2,13.8,7.3,12,4.8z"/><path d="M12,18.2c-0.4,0-0.7-0.3-0.7-0.7s0.3-0.7,0.7-0.7c1.3,0,2.4-1.1,2.4-2.4c0-0.4,0.3-0.7,0.7-0.7c0.4,0,0.7,0.3,0.7,0.7C15.8,16.5,14.1,18.2,12,18.2z"/>
      </symbol>
      <symbol id="icon-github" viewBox="0 0 32.6 31.8">
        <title>github</title>
        <path d="M16.3,0C7.3,0,0,7.3,0,16.3c0,7.2,4.7,13.3,11.1,15.5c0.8,0.1,1.1-0.4,1.1-0.8c0-0.4,0-1.4,0-2.8c-4.5,1-5.5-2.2-5.5-2.2c-0.7-1.9-1.8-2.4-1.8-2.4c-1.5-1,0.1-1,0.1-1c1.6,0.1,2.5,1.7,2.5,1.7c1.5,2.5,3.8,1.8,4.7,1.4c0.1-1.1,0.6-1.8,1-2.2c-3.6-0.4-7.4-1.8-7.4-8.1c0-1.8,0.6-3.2,1.7-4.4C7.4,10.7,6.8,9,7.7,6.8c0,0,1.4-0.4,4.5,1.7c1.3-0.4,2.7-0.5,4.1-0.5c1.4,0,2.8,0.2,4.1,0.5c3.1-2.1,4.5-1.7,4.5-1.7c0.9,2.2,0.3,3.9,0.2,4.3c1,1.1,1.7,2.6,1.7,4.4c0,6.3-3.8,7.6-7.4,8c0.6,0.5,1.1,1.5,1.1,3c0,2.2,0,3.9,0,4.5c0,0.4,0.3,0.9,1.1,0.8c6.5-2.2,11.1-8.3,11.1-15.5C32.6,7.3,25.3,0,16.3,0z"/>
      </symbol>
    </svg>
    <main>
      <div class="content content--fixed">
        <header class="codrops-header">
          <div class="codrops-links">
            <a class="codrops-icon codrops-icon--prev" href="https://tympanus.net/Development/TooltipAnimations/" title="Previous Demo"><svg class="icon icon--arrow"><use xlink:href="#icon-arrow"></use></svg></a>
            <a class="codrops-icon codrops-icon--drop" href="https://tympanus.net/codrops/?p=31349" title="Back to the article"><svg class="icon icon--drop"><use xlink:href="#icon-drop"></use></svg></a>
          </div>
          <h1 class="codrops-header__title">Letter Effects &amp; Interaction Ideas</h1>
        </header>
        <p class="codrops-header__tagline">
          <a class="github" href="https://github.com/okcjosh/" title="Find me on GitHub"><svg class="icon icon--github"><use xlink:href="#icon-github"></use></svg></a>
          Some playful typographic (hover) animations</p>
        <p class="deco">Leve fit, quod bene fertur, onus.</p>
      </div>
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100" height="100"  xml:space="preserve" id="canvas1">
    <!-- Generated by PaintCode - http://www.paintcodeapp.com -->

        <!-- This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes. -->

    <g id="canvas1-coffeCupssvgGroup">
        <g id="canvas1-group18">
            <path id="canvas1-bezier114" stroke="none" fill="rgb(0, 0, 0)" d="M 78,80.83 C 70.82,87.88 60.07,92.37 48.07,92.37 36.43,92.37 25.98,88.15 18.8,81.45 13.06,82.93 9.62,84.82 9.62,86.89 9.62,91.61 27.58,95.44 49.74,95.44 71.9,95.44 89.86,91.61 89.86,86.89 89.86,84.52 85.32,82.37 78,80.83 Z M 78,80.83" />
            <path id="canvas1-bezier115" stroke="none" fill="rgb(0, 0, 0)" d="M 87.42,62.88 C 86.7,62.77 85.99,62.73 85.28,62.74 85.39,61.77 85.45,60.79 85.45,59.8 85.45,59.21 85.43,58.62 85.39,58.03 L 85.36,58.03 C 84.7,52.48 68.25,48.03 48.06,48.03 27.45,48.03 10.74,52.67 10.74,58.38 10.74,58.4 10.74,58.42 10.74,58.44 10.72,58.89 10.7,59.35 10.7,59.8 10.7,76.96 27.43,90.86 48.07,90.86 60.7,90.86 71.87,85.66 78.63,77.69 80.12,78.66 81.94,79.36 83.98,79.65 90.06,80.51 95.76,77.45 96.71,72.82 97.66,68.19 93.5,63.74 87.42,62.88 Z M 73.11,65.08 C 75.02,64 76.11,62.79 76.11,61.5 76.11,57.11 63.55,53.55 48.06,53.55 32.57,53.55 20.02,57.11 20.02,61.5 20.02,62.79 21.1,64 23.01,65.08 18.38,63.52 15.6,61.52 15.6,59.35 15.6,54.37 30.13,50.34 48.06,50.34 65.99,50.34 80.53,54.37 80.53,59.35 80.53,61.52 77.75,63.52 73.11,65.08 Z M 92.12,72.17 C 91.44,75.47 86.93,77.58 82.03,76.88 81.21,76.77 80.44,76.58 79.72,76.33 82.29,72.95 83.75,70.26 84.59,66.16 89.25,66.98 92.78,68.97 92.12,72.17 Z M 92.12,72.17" />
            <path id="canvas1-bezier116" stroke="none" fill="rgb(0, 0, 0)" d="M 91.64,80.78 L 91.04,80.78 C 94.27,82.32 96.11,84.05 96.11,85.89 96.11,92.08 75.35,97.11 49.74,97.11 24.13,97.11 3.37,92.09 3.37,85.89 3.37,84.05 5.2,82.32 8.43,80.78 L 7.82,80.78 C 2.71,82.78 -0.26,85.17 -0.26,87.73 -0.26,94.76 22.13,100.46 49.74,100.46 77.35,100.46 99.74,94.76 99.74,87.73 99.74,85.17 96.76,82.78 91.64,80.78 Z M 91.64,80.78" />
        </g>
        <path id="canvas1-bezier118" stroke="none" fill="rgb(0, 0, 0)" d="M 47.7,40.31 C 38.5,36.79 32.93,28.56 32.93,19.88 L 32.93,19.88 C 32.93,17.07 33.52,14.21 34.75,11.46 L 34.75,11.46 C 37.83,4.55 45.05,0.37 52.66,0.37 L 52.66,0.37 C 55.12,0.37 57.63,0.81 60.05,1.74 L 60.05,1.74 C 66.13,4.06 69.8,9.49 69.8,15.23 L 69.8,15.23 C 69.8,17.08 69.42,18.97 68.61,20.79 L 68.61,20.79 C 66.55,25.39 61.75,28.17 56.69,28.16 L 56.69,28.16 C 55.05,28.16 53.38,27.87 51.77,27.26 L 51.77,27.26 C 47.69,25.7 45.23,22.05 45.23,18.21 L 45.23,18.21 C 45.23,16.96 45.49,15.69 46.03,14.47 L 46.03,14.47 C 47.42,11.36 50.68,9.47 54.11,9.47 L 54.11,9.47 C 55.22,9.47 56.35,9.67 57.44,10.09 L 57.44,10.09 C 60.24,11.16 61.93,13.66 61.93,16.3 L 61.93,16.3 C 61.93,17.16 61.75,18.02 61.38,18.86 L 61.38,18.86 C 60.41,21.03 58.15,22.34 55.76,22.34 L 55.76,22.34 C 54.99,22.34 54.2,22.2 53.44,21.91 L 53.44,21.91 C 51.46,21.15 50.26,19.39 50.26,17.52 L 50.26,17.52 C 50.26,16.92 50.39,16.3 50.65,15.71 L 50.65,15.71 C 51.35,14.15 52.98,13.2 54.7,13.2 L 54.7,13.2 C 55.26,13.2 55.83,13.3 56.38,13.51 L 56.38,13.51 C 57.07,13.78 57.4,14.51 57.11,15.15 L 57.11,15.15 C 56.82,15.79 56.03,16.1 55.34,15.83 L 55.34,15.83 C 55.12,15.75 54.92,15.71 54.7,15.71 L 54.7,15.71 C 54.05,15.72 53.43,16.07 53.16,16.67 L 53.16,16.67 C 53.04,16.95 52.98,17.23 52.98,17.52 L 52.98,17.52 C 52.98,18.4 53.54,19.24 54.48,19.59 L 54.48,19.59 C 54.9,19.75 55.33,19.83 55.76,19.83 L 55.76,19.83 C 57.08,19.83 58.34,19.1 58.87,17.9 L 58.87,17.9 C 59.11,17.37 59.22,16.83 59.22,16.3 L 59.22,16.3 C 59.22,14.65 58.16,13.08 56.41,12.41 L 56.41,12.41 C 55.65,12.12 54.88,11.99 54.11,11.99 L 54.11,11.99 C 51.74,11.99 49.5,13.28 48.54,15.43 L 48.54,15.43 C 48.13,16.34 47.94,17.28 47.94,18.21 L 47.94,18.21 C 47.94,21.06 49.78,23.78 52.81,24.94 L 52.81,24.94 C 54.08,25.42 55.4,25.65 56.69,25.65 L 56.69,25.65 C 60.68,25.65 64.48,23.46 66.1,19.83 L 66.1,19.83 C 66.77,18.32 67.09,16.76 67.09,15.23 L 67.09,15.23 C 67.09,10.48 64.05,5.98 59.01,4.06 L 59.01,4.06 C 56.93,3.26 54.78,2.88 52.66,2.88 L 52.66,2.88 C 46.12,2.89 39.91,6.47 37.26,12.42 L 37.26,12.42 C 36.16,14.86 35.65,17.39 35.65,19.88 L 35.65,19.88 C 35.65,27.57 40.58,34.87 48.74,37.99 L 48.74,37.99 48.74,37.99 C 49.43,38.25 49.76,38.99 49.47,39.63 L 49.47,39.63 C 49.26,40.11 48.75,40.4 48.22,40.4 L 48.22,40.4 C 48.05,40.4 47.87,40.37 47.7,40.31 L 47.7,40.31 Z M 47.7,40.31" />
    </g>
</svg>
      <section class="content content--layout">
        <h2 class="word word--magneto">Kabinka</h2>
      </section>
    </main>
    </body>
  </div>
</template>

<script>
  require('../assets/fancy/js/demo.js');
  require('../assets/fancy/js/demo1');
  require('../assets/fancy/js/demo2.js');
  require('../assets/fancy/js/demo3.js');
  require('../assets/fancy/js/demo4.js');
  require('../assets/fancy/js/imagesloaded.pkgd.min.js');
  const charming = require('charming')
  const anime = require('animejs');
  let cssScript = function () {
    {
      setTimeout(() => document.body.classList.add('render'), 60)
      const navdemos = document.querySelectorAll('nav.demos > .demo')
      Array.from(navdemos).forEach(link => link.addEventListener('click', (ev) => {
        ev.preventDefault()
        document.body.classList.remove('render')
        document.body.addEventListener('transitionend', () => window.location = ev.target.href)
      }))
    }
    {
      // from http://www.quirksmode.org/js/events_properties.html#position
      const getMousePos = (ev) => {
        let posx = 0
        let posy = 0
        if (!ev) ev = window.event
        if (ev.pageX || ev.pageY) 	{
          posx = ev.pageX
          posy = ev.pageY
        } else if (ev.clientX || ev.clientY) 	{
          posx = ev.clientX + document.body.scrollLeft + document.documentElement.scrollLeft
          posy = ev.clientY + document.body.scrollTop + document.documentElement.scrollTop
        }
        return { x: posx, y: posy }
      }

      class Letter {
        constructor (letter) {
          this.DOM = {}
          this.CONFIG = {
            color: '#fff',
            trailDelay: 0,
            maxScaleX: 1,
            minScaleX: 0.8,
            maxScaleY: 1.6,
            minScaleY: 1,
            stretchTransition: 'transform 0.4s cubic-bezier(0.1,1,0.3,1)',
            reverseAnim: {
              duration: 1000,
              easing: 'easeOutElastic',
              elasticity: 600,
              scaleY: 1,
              scaleX: 1
            }
          }
          this.DOM.letter = letter
          this.layout()
          this.initEvents()
        }
        layout () {
          this.DOM.letterInner = document.createElement('span')
          this.DOM.letterInner.innerHTML = this.DOM.letter.innerHTML
          this.DOM.letter.innerHTML = ''
          this.DOM.svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
          this.DOM.svg.setAttribute('width', '100px')
          this.DOM.svg.setAttribute('height', '150px')
          this.DOM.svg.setAttribute('viewBox', '0 0 100 150')
          this.DOM.svg.setAttribute('preserveAspectRatio', 'xMaxYMax meet')

          const r = 11
          for (let i = 0; i < 3; i++) {
            const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle')
            circle.setAttribute('cx', 39 * i + r)
            circle.setAttribute('cy', 139)
            circle.setAttribute('r', r)
            this.DOM.svg.appendChild(circle)
          };
          this.DOM.circles = Array.from(this.DOM.svg.querySelectorAll('circle'))
          this.DOM.letter.appendChild(this.DOM.svg)
          this.DOM.letter.appendChild(this.DOM.letterInner)
        }
        stretch (ev) {
          const mousepos = getMousePos(ev)
          const docScrolls = {left: document.body.scrollLeft + document.documentElement.scrollLeft, top: document.body.scrollTop + document.documentElement.scrollTop}
          const bounds = this.DOM.letter.getBoundingClientRect()
          const relmousepos = {
            x: mousepos.x - bounds.left - docScrolls.left,
            y: mousepos.y - bounds.top - docScrolls.top
          }
          anime.remove(this.DOM.letterInner)
          this.DOM.letterInner.style.transformOrigin = '50% 100%'
          const sX = (this.CONFIG.maxScaleX - this.CONFIG.minScaleX) / bounds.height * relmousepos.y + this.CONFIG.minScaleX
          const sY = (this.CONFIG.minScaleY - this.CONFIG.maxScaleY) / bounds.height * relmousepos.y + this.CONFIG.maxScaleY
          this.DOM.letterInner.style.transform = `scaleX(${sX}) scaleY(${sY})`
        }
        initEvents () {
          this.mouseenterFn = () => this.mouseTimeout = setTimeout(() => {
            this.isActive = true
            requestAnimationFrame(() => this.DOM.letterInner.style.transition = this.CONFIG.stretchTransition)
          }, 50)

          this.mousemoveFn = (ev) => {
            if (!this.isActive) return
            requestAnimationFrame(() => this.stretch(ev))
          }
          this.mouseleaveFn = () => {
            clearTimeout(this.mouseTimeout)
            if (!this.isActive) return
            this.isActive = false
            this.DOM.letterInner.style.transition = 'none'
            requestAnimationFrame(() => {
              const scaleYCurrent = anime.getValue(this.DOM.letterInner, 'scaleY')

              anime.remove(this.DOM.letterInner)
              let animOpts = {targets: this.DOM.letterInner}
              anime(Object.assign(animOpts, this.CONFIG.reverseAnim))

              if (scaleYCurrent > 1.4) {
                anime.remove(this.DOM.circles)
                anime({
                  targets: this.DOM.circles,
                  duration: (t, i) => { return anime.random(300, 400) },
                  easing: [0.1, 1, 0.3, 1],
                  delay: (t, i) => { return i * 40 + parseInt(this.CONFIG.trailDelay) },
                  opacity: [
                    {value: 1, duration: 10, easing: 'linear'},
                    {value: 0, duration: 200, easing: 'linear'}
                  ],
                  translateY: (t, i) => { return [100, anime.random(-250, -120)] },
                  scaleX: [2, 0.3],
                  scaleY: [2, 2]
                })
              }
            })
          }
          this.DOM.letter.addEventListener('mouseenter', this.mouseenterFn)
          this.DOM.letter.addEventListener('mousemove', this.mousemoveFn)
          this.DOM.letter.addEventListener('mouseleave', this.mouseleaveFn)
          this.DOM.letter.addEventListener('touchstart', this.mouseenterFn)
          this.DOM.letter.addEventListener('touchend', this.mouseleaveFn)
        }
      }

      class Word {
        constructor (word) {
          this.DOM = {}
          this.DOM.word = word
          this.layout()
        }
        layout () {
          charming(this.DOM.word, {classPrefix: 'letter'})
          Array.from(this.DOM.word.querySelectorAll('span')).forEach(letter => new Letter(letter))
        }
      }

      Array.from(document.querySelectorAll('.word')).forEach((word) => new Word(word))
    };
  }
  export default {
    name: 'svg',
    data () {
      return {
        msg: 'Welcome to Your Vue.js PWA'
      }
    },
    mounted () {
      cssScript()
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  @import '../assets/fancy/css/normalize.css';
  @import '../assets/fancy/css/kidnap.css';
  @import '../assets/fancy/css/magneto.css';
  @import '../assets/fancy/css/demo.css';
  @import '../assets/fancy/css/redraw.css';
  @import '../assets/fancy/css/swing.css';
</style>
